language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

branches:
  only:
    - master


before_script:
  - export phpConfigFile=`php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - git clone git://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment
  - git clone git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction
  - mv build-environment/typo3conf .
  - git clone git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/
  - mkdir fileadmin
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi

  - build-environment/install-php-extension.sh igbinary > /dev/null
  - printf "no\n" | build-environment/install-php-extension.sh memcache  > /dev/null
  - printf "no\n" | build-environment/install-php-extension.sh apc > /dev/null
  - echo "apc.enable_cli = 1" >> $phpConfigFile
  - echo "apc.slam_defense = 0" >> $phpConfigFile
  - (mkdir phpredis-build && cd phpredis-build && git clone --depth 1 git://github.com/nicolasff/phpredis.git && cd phpredis && phpize && ./configure && make && sudo make install && cd ../../) > /dev/null
#  - [ -z "`grep redis.so $phpConfigFile`" ] && echo "extension=\"redis.so\"" >> $phpConfigFile


script: php $PWD/typo3/cli_dispatch.phpsh phpunit $PWD/tests/
