language: php
php:
  - 5.3

env:
  - DB=mysql
#  - DB=pgsql

before_script:
  - git submodule update --init --recursive
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < tests/t3lib/fixtures/introduction.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < tests/t3lib/fixtures/cli_users.sql; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS typo3_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database typo3_test;" -U postgres; fi
  - mkdir -p typo3conf/ext typo3temp uploads
  - cp tests/t3lib/fixtures/localconf.php typo3conf/localconf.php
  - mv tests/t3lib/fixtures/phpunit typo3conf/ext/

script: php typo3/cli_dispatch.phpsh phpunit tests/